version: 2.1
defaults: &defaults
  machine:
    image: circleci/classic:edge

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ./scripts/ci
          when: always
      - store_artifacts:
          path: ~/video

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  default-workflow:
    jobs:
      - test

      - publish:
          requires:
            - test
          filters:
            tags:
              only:
                - /^v.+/
            branches:
              only:
                - master
