#!/bin/bash

lein run -m shadow.cljs.devtools.cli --npm watch tests &
for n in {1..15}; do
  ls target/integration/main.js &>/dev/null && break
  echo "Not compiled yet, waiting..."
  sleep 10
done

export DISPLAY=:99
Xvfb :99 &
node integration_test.js
ret=$?

echo -e "(System/exit 0)\n" | nc localhost 2233
exit $ret
