#!/bin/bash

apt-get update
apt-get install -y curl
apt-get install -y xvfb ffmpeg netcat xz-utils openjdk-11-jdk

cd /tmp
curl https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz | tar -xJ
cp -a /tmp/node-v10.16.3-linux-x64/* /usr
rm -R /tmp/node-v10.16.3-linux-x64
cd /work

npm install
npx shadow-cljs watch integration fixture &
for n in {1..25}; do
  ls target/fixture.js target/integration/main.js &>/dev/null && break
  echo "Not compiled yet, waiting..."
  sleep 10
done

ls target/fixture.js target/integration/main.js || exit 1
echo "Fixture app compiled, running the fixture app"
node target/fixture.js &

export DISPLAY=:99
Xvfb -screen 0 1024x768x24+32 :99 &
# mkdir ~/video
# nohup ffmpeg -video_size 1024x768 -f x11grab -i :99.0 ~/video/out.mpg &

echo "Running tests"
node integration_test.js
ret=$?

echo -e "(System/exit 0)\n" | nc localhost 2233
exit $ret
